Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/sripathisridhar/PycharmProjects/tau-av/baseline/main.py", line 76, in <module>
    train(model, train_loader, device, optimizer, loss_fn, config['N_EPOCHS'], val_loader)
  File "/Users/sripathisridhar/PycharmProjects/tau-av/baseline/train.py", line 32, in train
    start_time = time.time()
AttributeError: type object 'datetime.time' has no attribute 'time'
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/sripathisridhar/PycharmProjects/tau-av/baseline/main.py", line 76, in <module>
    train(model, train_loader, device, optimizer, loss_fn, config['N_EPOCHS'], val_loader)
  File "/Users/sripathisridhar/PycharmProjects/tau-av/baseline/train.py", line 32, in train
    start_time = time.time()
AttributeError: type object 'datetime.time' has no attribute 'time'
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/sripathisridhar/PycharmProjects/tau-av/baseline/main.py", line 76, in <module>
    train(model, train_loader, device, optimizer, loss_fn, config['N_EPOCHS'], val_loader)
  File "/Users/sripathisridhar/PycharmProjects/tau-av/baseline/train.py", line 32, in train
    start_time = time.time()
AttributeError: type object 'datetime.time' has no attribute 'time'